### ISSUE TITLE
Gutenberg Gait Database, a ground reaction force database of level overground walking in healthy individuals

### ISSUE THREAD

**Issue by fabian-horst** [modenaxe/awesome-biomechanics#23]
Description: The Gutenberg Gait Database comprises data of 350 healthy individuals. The database contains ground reaction force (GRF) and center of pressure (COP) data of two consecutive steps measured - by two force plates embedded in the ground - during level overground walking at self-selected walking speed. 

Paper: Horst, F., Slijepcevic, D., Simak, M. & Schöllhorn, W. I. Gutenberg Gait Database, a ground reaction force database of level overground walking in healthy individuals. Sci Data 8, 232 (2021). https://doi.org/10.1038/s41597-021-01014-6

Dataset: Horst, F., Slijepcevic, D., Simak, M. & Schöllhorn, W. I. Gutenberg Gait Database: A ground reaction force database of level overground walking in healthy individuals. figshare https://doi.org/10.6084/m9.figshare.c.5311538 (2021).

**Comment by modenaxe** [comment]
thank you @fabian-horst , added!
