### ISSUE TITLE
404 link not found

### ISSUE THREAD

**Issue by GianEng** [modenaxe/awesome-biomechanics#27]
Hi!
the link of "learning"-"Lectures on optimal control by Anil Rao (University of Florida)" is not working

http://www.anilvrao.com/Optimal-Control-Videos.html
https://github.com/modenaxe/awesome-biomechanics

Bye!
GianEng

**Comment by modenaxe** [comment]
Hello @GianEng,
thank you for letting me know, I will have a look if alternative links are available.
Luca
