### ISSUE TITLE
add Complete Inertial Pose Dataset

### ISSUE THREAD

**Issue by modenaxe** [modenaxe/awesome-biomechanics#34]
dataset: https://zenodo.org/record/5801928#.YhYu0ehBz4c
paper: https://arxiv.org/pdf/2202.06164.pdf
code: https://github.com/ManuelPalermo/HumanInertialPose
by @ManuelPalermo

**Comment by ManuelPalermo** [comment]
Hi @modenaxe, thank you for the interest in our work! I have created a PR adding information relative to the dataset, code and paper, let me know if you agree!

**Comment by modenaxe** [comment]
@ManuelPalermo thank you for contributing to the repository! PR merged! :)
