### ISSUE TITLE
need an automatic Table of Contents generator

### ISSUE THREAD

**Issue by modenaxe** [modenaxe/awesome-biomechanics#4]
I found this one: ~~https://ecotrust-canada.github.io/markdown-toc~~ but it does not handle well spaces and colons in emoji `:name:`.

**Comment by modenaxe** [comment]
This is the best one: https://luciopaiva.com/markdown-toc/

**Comment by jobindj** [comment]
Many text editors have good add-ons to create TOC. I find good ones on VS codes

**Comment by modenaxe** [comment]
@jobindj good advice, the Markdown extension of VS Code works indeed very well!
